[package]
name = "cairo"
version = "0.1.0"
authors = ["Jiahong Long <jiahong888long@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16"
cairo-rs = {version="0.9", features=["png"]}
